const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   STORE_USER_POST: "STORE_USER_POST",
   DELETE_USER_POST: "DELETE_USER_POST",
   UPDATE_INDEX_OF_CURRENT_POST: " UPDATE_INDEX_OF_CURRENT_POST",
};

export default actions;
